# Generated by Django 4.2.5 on 2024-01-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aioapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
