# Generated by Django 4.2.5 on 2024-01-19 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aioapp', '0003_user_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_Picture',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_Id',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Username',
            new_name='username',
        ),
    ]
