# Generated by Django 4.2.5 on 2024-01-19 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aioapp', '0004_rename_date_product_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_title',
        ),
    ]
