# Generated by Django 4.2.5 on 2024-01-23 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aioapp', '0005_rename_name_product_product_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bio',
            new_name='description',
        ),
    ]
