# Generated by Django 4.2.5 on 2024-01-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aioapp', '0006_rename_bio_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=87),
        ),
    ]
