# Generated by Django 4.2.5 on 2024-02-03 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aioapp', '0008_alter_user_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='username',
            new_name='user',
        ),
    ]
